### PR TITLE
AXIS API fixes

### PR DESCRIPTION
**Pull request by ch08532**
Updates to the AXIS sensor to provide better support to both AXIS VAPIX v2 and v3 API.  

AxisVideoOutput.java
  - Centralized url paths to AxisCameraDriver.js
  - Beautified source
  - Generate URLs on construction

AxisPTZOutput.java
  - Centralized url paths to AxisCameraDriver.js
  - Beautified source
  - Removed commented out code
  - Reading PTZ now supports VAPIX3

 AxisPTZControl.java
  - Centralized url paths to AxisCameraDriver.js

 AxisCameraDriver.java
  - Added URL path constants on top of class declaration
  - Modified path constants to work on VAPIX v2 and v3
  - Improved AXIS feature validation and detection on init

AxisCameraConfig.java
  - Centralized rtsp video paths to AxisCameraDriver.js

### CODE REVIEW

**Comment by mikebotts** [comment]
Super. Thanks Chris. We appreciate your help.

Have you been able to deploy the geospatial processing for PTZ video that allows you to know the geospatial orientation of the camera and to task the camera to look at a particular latitude-longitude-altitude? We have that working but we haven’t really exposed it much to the community yet but plan to try to clean that up and demonstrate the capability soon.  Let me know if your interested in being notified about that or are interested in helping with it.

Do you mind me adding you to the community as a contributor?

	https://opensensorhub.org/community/ <https://opensensorhub.org/community/>

Mike


Dr. Mike Botts
Botts Innovative Research, Inc.
http://www.botts-inc.com
http://opensensorhub.org
mike.botts@botts-inc.com

**Comment by ch08532** [comment]
Hi Mike,

I have not tested any of the tasking features via SPS  however I was able to at least visualise the PTZ data.  Feel free to add me as a contributor if the offer is still on the table.  I don't have much downtown in the near future but can help from time to time.

Cheers,

Chris

**Review by mikebotts — APPROVED** [review]
Checked by Mike Botts 2017-01-10. Thanks Chris.

**Comment by mikebotts** [comment]
Push Request from Chris Amadal checked and accepted.  Thanks Chris.

**Pull request merged**
